version: '3.8'
services:
  api:
    container_name: api_test
    build:
      context: .
      dockerfile: docker/api/Dockerfile

    restart: unless-stopped

    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - ${EXT_API_PORT}:5000
    command: [
      "poetry", "run", "uvicorn", "app:create_app",
      "--host", "0.0.0.0",
      "--port", '5000',
    ]

  redis:
    container_name: redis_test
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${REDIS_DATA_VOLUME}:/redis-data:/data


networks:
  default:
    name: shared-network
